const POINTS_PER_APPLY = 1000;
const EVENT_STATUS = Object.freeze({ SCHEDULED: '예정', ONGOING: '진행중', ENDED: '종료' });
const EVENT_STATUS_TRANSITIONS = Object.freeze({
  [EVENT_STATUS.SCHEDULED]: [EVENT_STATUS.ONGOING],
  [EVENT_STATUS.ONGOING]: [EVENT_STATUS.ENDED],
  [EVENT_STATUS.ENDED]: [],
});

module.exports = { POINTS_PER_APPLY, EVENT_STATUS, EVENT_STATUS_TRANSITIONS };
